// Job Scout — Feature catalog used by the Video Library page.
//
// One source of truth for "what features ship in Job Scout, and what
// market tool each one replaces." Each feature can optionally carry a
// `video_url` (Loom / YouTube / Vimeo URL) — when set, the Video Library
// card becomes a play-button thumbnail.
//
// Schema:
//   {
//     category: 'Sales & CRM',
//     summary: 'Short pitch for the category',
//     features: [{
//       name: 'Lead Setter',
//       icon: 'UserPlus',              // any lucide-react export
//       summary: '1-2 sentence description',
//       replaces: ['Calendly', 'Acuity'],
//       highlights: ['Mobile-first', 'GPS check-in'],
//       route: '/lead-setter',         // optional in-app deep link
//       video_url: null,               // null until we record one
//       status: 'shipped',             // 'shipped' | 'beta' | 'coming_soon'
//     }, ...]
//   }
//
// Update here, push, and the marketing page reflects automatically.

export const FEATURE_CATALOG = [
  {
    category: 'Sales & CRM',
    summary: 'Apollo-to-close: prospect, set, sell, and sign — all in one pipeline.',
    features: [
      {
        name: 'Prospect Scout',
        icon: 'Sparkles',
        summary: 'Your setters type plain English — "warehouses in Salt Lake County over 50 employees" — and Claude does the live web research, returning real businesses with cited sources. Tap to enrich with email + phone, multi-select, and bulk-import to the pipeline.',
        replaces: ['Apollo.io', 'ZoomInfo', 'Lusha', 'ChatGPT prospecting prompts'],
        highlights: ['Natural-language queries', 'Claude + live web search', 'Cited sources on every result', 'Per-candidate enrichment cache'],
        route: '/lead-setter',
        walkthrough: 'prospect-scout',
      },
      {
        name: 'Leads',
        icon: 'UserPlus',
        summary: 'The single intake for every potential customer — phone, web form, walk-in, HCP import, or Apollo — with owner, setter, source pay-per-lead, and conversion tracking.',
        replaces: ['HubSpot CRM', 'Pipedrive', 'HousecallPro lead intake'],
        highlights: ['Source attribution', 'Pay-per-lead tracking', 'Auto-convert to customer'],
        route: '/leads',
        walkthrough: 'leads',
      },
      {
        name: 'Lead Setter',
        icon: 'Headphones',
        summary: 'A dialer-style workspace where setters kanban through New / Contacted / Callback / Not Qualified leads and drag onto a calendar to book the rep, with setter commission paid per meeting that becomes a quote.',
        replaces: ['Calendly', 'Acuity', 'Apollo Dialer', 'Salesloft'],
        highlights: ['Drag-to-schedule calendar', 'Contact-attempt counter', 'Qualification rule'],
        route: '/lead-setter',
        walkthrough: 'lead-setter',
      },
      {
        name: 'Sales Pipeline',
        icon: 'GitBranch',
        summary: 'A Kanban pipeline (Appointment Set → Qualified → Quoted → Won) that lives on the lead itself — no separate deals table, no double entry.',
        replaces: ['Salesforce', 'HubSpot Deals', 'Pipedrive'],
        highlights: ['Lead = deal', 'Stage age tracking', 'Salesperson assignment'],
        route: '/pipeline',
        walkthrough: 'sales-pipeline',
      },
      {
        name: 'Estimates & Quotes',
        icon: 'FileText',
        summary: 'Build a multi-line quote (materials, labor, taxable flags, photos, notes, line-item discounts) and send a portal link the customer signs with a finger from their phone.',
        replaces: ['DocuSign', 'PandaDoc', 'Jobber quotes', 'HousecallPro estimates'],
        highlights: ['E-signature with IP + UA audit', 'Photo per line', 'Formal proposal PDF', 'Email-tracking pixel'],
        route: '/estimates',
        walkthrough: 'estimates',
      },
      {
        name: 'Quote Follow-ups',
        icon: 'Send',
        summary: 'A cron job auto-emails customers who let a quote sit, and Arnie can recommend add-on services based on the original scope.',
        replaces: ['Mailchimp drip', 'Constant Contact automations'],
        highlights: ['Cron-driven', 'Arnie add-on recs', 'Stop on signature'],
        route: '/estimates',
        walkthrough: 'quote-followups',
      },
      {
        name: 'Customers',
        icon: 'Users',
        summary: 'Every customer file — contact, address, calendar display preference, payment methods on file, statement history, source system (HCP import or native), and full job timeline.',
        replaces: ['HousecallPro customers', 'Jobber clients', 'ServiceTitan customer hub'],
        highlights: ['Saved payment methods', 'Source-system traceability', 'Magic-link portal'],
        route: '/customers',
        walkthrough: 'customers',
      },
      {
        name: 'Customer Portal',
        icon: 'Globe',
        summary: 'A public, no-login URL where customers view quotes, approve with e-signature, pay invoices via Stripe link, and download statements — token-based with ESIGN-grade audit logging.',
        replaces: ['DocuSign', 'QuickBooks customer portal', 'HousecallPro portal'],
        highlights: ['No-login magic links', 'Document hash + IP audit', 'Stripe payment links'],
        route: null,
        walkthrough: 'customer-portal',
      },
      {
        name: 'Public Quote Landing',
        icon: 'ExternalLink',
        summary: 'Per-company /quote/:slug landing page Zach uses to capture lawn-care quote requests from anywhere on the web — even before the prospect is a lead.',
        replaces: ['Service Autopilot online quoting', 'LawnPro instant quotes'],
        highlights: ['Per-company slug', 'Public, no auth', 'Auto-creates lead'],
        route: null,
        walkthrough: 'public-quote',
      },
      {
        name: 'Communications Log',
        icon: 'MessageSquare',
        summary: 'A unified timeline of every email, SMS, signature event, and invoice-conversation thread tied to the customer or job.',
        replaces: ['HubSpot conversations', 'OpenPhone history'],
        highlights: ['Email tracking pixels', 'Per-invoice threads'],
        route: '/communications',
        walkthrough: 'communications-log',
      },
    ],
  },
  {
    category: 'Project & Job Management',
    summary: 'Schedule the crew, run the field, prove the work, close the job — all from a phone.',
    features: [
      {
        name: 'Jobs',
        icon: 'Briefcase',
        summary: 'Every won estimate becomes a job with line items, photos, signatures, job-costing rollups, source-system traceability, and an auto-close trigger when the invoice is paid.',
        replaces: ['HousecallPro jobs', 'Jobber jobs', 'ServiceTitan jobs'],
        highlights: ['Auto-close on payment', 'Job costing rollup', 'Lead → quote → job chain'],
        route: '/jobs',
        walkthrough: 'jobs',
      },
      {
        name: 'Job Sections',
        icon: 'Layers',
        summary: 'Break a big job into trackable sections (% of job, assigned tech, scheduled date, estimated vs actual hours) so PMs can dispatch chunk by chunk.',
        replaces: ['ServiceTitan project tracking', 'Buildertrend phases'],
        highlights: ['Per-section assignee', 'Estimated vs actual hours', 'Verified-by audit'],
        route: '/jobs',
        walkthrough: 'job-sections',
      },
      {
        name: 'Job Board (PM Setter)',
        icon: 'ClipboardList',
        summary: 'The Project Manager workspace — drag job sections onto crews and days like a Trello board, with allotted-hours guardrails so nobody gets double-booked.',
        replaces: ['When I Work scheduling', 'ServiceTitan dispatch board'],
        highlights: ['Drag-to-schedule', 'Allotted-hours math', 'Per-PM workspace'],
        route: '/job-board',
        walkthrough: 'job-board',
      },
      {
        name: 'Job Calendar',
        icon: 'Calendar',
        summary: 'A monthly/weekly calendar of every scheduled job and section, color-coded by status and PM.',
        replaces: ['Google Calendar', 'HousecallPro calendar', 'Jobber calendar'],
        highlights: ['Drag-to-reschedule', 'Color by status'],
        route: null,
        walkthrough: 'job-calendar',
      },
      {
        name: 'Field Scout',
        icon: 'Compass',
        summary: "The mobile field-tech home base — today's jobs, one-tap clock in/out tied to a specific job, photo capture, and signature-on-glass — works offline with sync queue.",
        replaces: ['HousecallPro mobile', 'Jobber mobile', 'ServiceTitan Mobile'],
        highlights: ['Offline-first', 'Job-linked clock', 'Photo + signature capture'],
        route: '/field-scout',
        walkthrough: 'field-scout',
      },
      {
        name: 'Routes & Route Calendar',
        icon: 'Route',
        summary: 'Group jobs into optimized day-routes, see them on a map and calendar, and dispatch a crew to a multi-stop route.',
        replaces: ['OptimoRoute', 'Routific', 'ServiceTitan routing'],
        highlights: ['Multi-stop routes', 'Map + calendar view'],
        route: '/routes',
        walkthrough: 'routes',
      },
      {
        name: 'Appointments',
        icon: 'CalendarCheck',
        summary: 'Every scheduled meeting (sales call, site visit, install kickoff) with multi-salesperson support and Google Calendar two-way sync.',
        replaces: ['Calendly', 'Acuity', 'Google Calendar'],
        highlights: ['Multi-salesperson', 'Google Calendar OAuth', 'Outcome tracking'],
        route: '/appointments',
      },
      {
        name: 'Bookings',
        icon: 'CalendarDays',
        summary: "Self-serve booking pages where leads pick a slot off your team's real availability — like Calendly but stitched into the lead pipeline.",
        replaces: ['Calendly', 'Acuity', 'HubSpot Meetings'],
        highlights: ['Real availability', 'Auto-create lead'],
        route: null,
      },
      {
        name: 'Photos & Signatures',
        icon: 'Camera',
        summary: 'Tap-to-photo per quote line, job line, or audit area, plus draw-on-glass customer signatures saved with IP, UA, and timestamp for ESIGN compliance.',
        replaces: ['CompanyCam', 'DocuSign signature', 'Adobe Sign'],
        highlights: ['Per-line photos', 'ESIGN audit fields', 'Offline queue'],
        route: null,
      },
      {
        name: 'Document Rules & Packages',
        icon: 'FileStack',
        summary: 'Define which PDF forms get auto-attached to which service type — utility forms, ICA, handbook, packets — with field mapping so the system pre-fills them.',
        replaces: ['DocuSign Templates', 'PandaDoc templates'],
        highlights: ['PDF field mapping', 'Service-type-driven packages'],
        route: null,
        walkthrough: 'document-rules',
      },
    ],
  },
  {
    category: 'Lighting & Energy',
    summary: 'Lenard the Lighting Auditor — snap, identify, calculate the rebate, file the form.',
    features: [
      {
        name: 'Lighting Audits',
        icon: 'Lightbulb',
        summary: 'Walk a building, photograph each area, let AI identify fixtures + count bulbs, and produce a turnkey LED retrofit proposal with rebate math baked in.',
        replaces: ['Snugg Pro', 'Rifeline', 'manual Excel audits'],
        highlights: ['AI fixture ID', 'Per-area photos', 'Customer signature on completion'],
        route: null,
        walkthrough: 'lighting-audits',
      },
      {
        name: 'Fixture Types',
        icon: 'Lamp',
        summary: 'Your catalog of existing/proposed fixtures with wattage, lamp count, DLC documentation URL, and per-fixture replacement defaults.',
        replaces: ['DLC Premium spreadsheets', 'manual fixture libraries'],
        highlights: ['DLC doc links', 'Baseline vs proposed math'],
        route: null,
        walkthrough: 'fixture-types',
      },
      {
        name: 'Utility Providers',
        icon: 'Zap',
        summary: 'Per-state utility company database — SRP, RMP, APS, PG&E — with rate schedules and contact info pre-loaded.',
        replaces: ['DSIRE database', 'manual utility research'],
        highlights: ['Rate schedule lookups', 'Per-provider programs'],
        route: null,
      },
      {
        name: 'Utility Programs',
        icon: 'FileCheck',
        summary: 'Every active rebate program (RMP Wattsmart, SRP Custom, etc.) with source-year tracking, prescriptive measure tables, and PDF form binding.',
        replaces: ['Rifeline program lookup', 'manual rebate calculators'],
        highlights: ['Source-year tracking', 'Form auto-fill'],
        route: null,
        walkthrough: 'utility-programs',
      },
      {
        name: 'Rebate / Incentive Measures',
        icon: 'Coins',
        summary: 'The line-item rebate table — per measure code, baseline wattage, proposed wattage, $ per unit, caps — the engine Lenard uses to calculate the exact rebate.',
        replaces: ['Snugg Pro measure libraries', 'Rifeline rate tables'],
        highlights: ['Prescriptive + custom measures', 'RMP measure lookup', 'Cap math'],
        route: null,
        walkthrough: 'rebate-measures',
      },
      {
        name: 'Utility Invoices',
        icon: 'Receipt',
        summary: 'Special invoice type for utility-payable rebates with editable material/labor split, customer-portion math, and processor commission tracking.',
        replaces: ['QuickBooks workaround invoices', 'Excel rebate trackers'],
        highlights: ['70/30 split editable', 'Processor commission', 'Link to customer'],
        route: null,
        walkthrough: 'utility-invoices',
      },
      {
        name: 'Public Lenard Agent Pages',
        icon: 'Sparkles',
        summary: 'Per-utility public landing pages (/agent/lenard-az-srp, /agent/lenard-ut-rmp) where prospects upload photos and get an instant LED rebate estimate — no login.',
        replaces: ['Custom marketing landing pages', 'EnergySavvy widgets'],
        highlights: ['Public no-auth', 'Per-utility branding', 'Anon signature capture'],
        route: null,
        walkthrough: 'lenard-public-pages',
      },
      {
        name: 'Dougie OCR Corrections',
        icon: 'BookOpen',
        summary: 'An invisible learning loop — every time someone fixes an AI mis-read on an audit, Dougie remembers it as few-shot context so the next audit gets it right.',
        replaces: ['manual QA', 'model retraining cycles'],
        highlights: ['Few-shot learning', 'Per-company corrections'],
        route: null,
        walkthrough: 'dougie',
      },
    ],
  },
  {
    category: 'Fleet & Vehicles',
    summary: 'Freddy the Fleet Manager — vehicles verified, maintenance managed, fuel logged.',
    features: [
      {
        name: 'Fleet',
        icon: 'Truck',
        summary: 'Every vehicle on your roster — VIN, plate, assigned driver, status, photo inspections — all in one mobile-friendly grid.',
        replaces: ['Fleetio', 'Samsara', 'Fleet Complete'],
        highlights: ['Photo inspections', 'Driver assignment', 'Per-vehicle history'],
        route: '/fleet',
        walkthrough: 'fleet',
      },
      {
        name: 'Fleet Maintenance & Costs',
        icon: 'Wrench',
        summary: 'Track every oil change, repair, and recurring maintenance event with cost rollups per vehicle so you know which truck is bleeding you.',
        replaces: ['Fleetio Maintenance', 'Samsara Maintenance'],
        highlights: ['Cost-per-vehicle', 'Service reminders'],
        route: '/agents/freddy/costs',
      },
      {
        name: 'Fuel Logs',
        icon: 'Fuel',
        summary: 'Driver-friendly fuel fill-up logging — gallons, $/gal, odometer, station, photo — with MPG and cost-per-mile auto-computed.',
        replaces: ['WEX fleet card reports', 'Fleetio fuel'],
        highlights: ['Mobile entry', 'MPG math', 'Cost-per-mile'],
        route: '/agents/freddy/costs',
      },
      {
        name: 'Live Tracking',
        icon: 'MapPin',
        summary: 'See trucks on a live map using driver phone GPS — no expensive hardware dongle required.',
        replaces: ['Samsara GPS', 'Verizon Connect'],
        highlights: ['Phone GPS only', 'No hardware needed'],
        route: '/agents/freddy/tracking',
      },
      {
        name: 'Trips',
        icon: 'Map',
        summary: 'Auto-logged driver trips with start/end address, miles, and per-trip job linkage for billable mileage.',
        replaces: ['MileIQ', 'Everlance'],
        highlights: ['Auto-trip detection', 'Job linkage'],
        route: '/agents/freddy/trips',
      },
      {
        name: 'Drivers',
        icon: 'UserCheck',
        summary: 'Driver scorecard — speeding, hard braking, mileage, fuel efficiency — per employee.',
        replaces: ['Samsara driver scorecard', 'Lytx'],
        highlights: ['Per-driver score', 'Coaching triggers'],
        route: '/agents/freddy/drivers',
      },
      {
        name: 'Fleet Alerts',
        icon: 'Bell',
        summary: 'Configurable alerts for low fuel, geofence breaches, maintenance overdue, and after-hours use.',
        replaces: ['Samsara alerts', 'Fleetio reminders'],
        highlights: ['Geofence', 'Maintenance overdue', 'Custom rules'],
        route: '/agents/freddy/alerts',
      },
      {
        name: 'Fleet Calendar',
        icon: 'CalendarRange',
        summary: 'A calendar of vehicle bookings, maintenance windows, and rental returns so two crews never grab the same truck.',
        replaces: ['Fleetio reservations'],
        highlights: ['Conflict detection', 'Maintenance windows'],
        route: null,
      },
    ],
  },
  {
    category: 'Lawn Care',
    summary: 'Zach the Yard Yeti — measure twice, mow once.',
    features: [
      {
        name: 'Properties',
        icon: 'Home',
        summary: 'One file per lawn — turf sqft, mow cadence, gate code, dog, sprinkler quirks, hazards — so any crew can show up ready.',
        replaces: ['Service Autopilot properties', 'LawnPro properties', 'Jobber'],
        highlights: ['Gate codes + dog notes', 'Per-property obstacles', 'Customer link'],
        route: '/agents/zach',
        walkthrough: 'zach-properties',
      },
      {
        name: 'Visits Log',
        icon: 'ClipboardCheck',
        summary: 'Every mow / cleanup visit logged with crew, duration, weather, and notes — the audit trail customers can see in their portal.',
        replaces: ['Service Autopilot visit log', 'LawnPro work orders'],
        highlights: ['Crew + duration', 'Weather logged'],
        route: '/agents/zach/visits',
        walkthrough: 'zach-visits',
      },
      {
        name: 'Treatments',
        icon: 'Sprout',
        summary: 'Seasonal application schedule — fert rounds, pre-emergent, grub control, aeration — with per-round application notes for state pesticide reporting.',
        replaces: ['Service Autopilot chemical tracker', 'Real Green'],
        highlights: ['Round scheduling', 'Application records'],
        route: '/agents/zach/treatments',
        walkthrough: 'zach-treatments',
      },
      {
        name: 'Lawn Pricing',
        icon: 'DollarSign',
        summary: "Per-sqft pricing tiers and per-service rates that drive Zach's instant quote engine.",
        replaces: ['Service Autopilot price book', 'manual sqft pricing'],
        highlights: ['Sqft-tier pricing', 'Per-service rates'],
        route: '/agents/zach/pricing',
        walkthrough: 'zach-pricing',
      },
      {
        name: 'AI Yard Measure',
        icon: 'Scan',
        summary: "Drop a pin on a property, AI traces turf area from aerial imagery, instant quote drops in the customer's email — Zach's killer feature.",
        replaces: ['GreenPal', 'Lawnstarter measure', 'Service Autopilot Measure'],
        highlights: ['AI turf detection', 'Aerial measurement', 'Instant quote'],
        route: null,
        walkthrough: 'yard-measure',
      },
    ],
  },
  {
    category: 'Inventory & Catalog',
    summary: "Your product catalog, components, and warehouse — Lenard's parts list lives here.",
    features: [
      {
        name: 'Products & Services',
        icon: 'Package',
        summary: 'Your full catalog — products, services, software, with cost, labor rate binding, taxable flag, product groups, photos, and DLC docs.',
        replaces: ['QuickBooks items', 'HousecallPro price book', 'Jobber price book'],
        highlights: ['Labor rate binding', 'Product groups', 'Photo + DLC enrichment'],
        route: '/products',
        walkthrough: 'products-services',
      },
      {
        name: 'Product Components / BOMs',
        icon: 'Boxes',
        summary: "Multi-component products (a 'troffer retrofit' is 1 housing + 1 driver + 4 LED tubes) auto-explode for cost rollup and inventory pull.",
        replaces: ['Fishbowl BOMs', 'QuickBooks assemblies'],
        highlights: ['Auto-explode on quote', 'Cost rollup'],
        route: '/products',
      },
      {
        name: 'Inventory',
        icon: 'Warehouse',
        summary: 'Track stock-on-hand, locations, and consumption per job — assign materials to a job line and watch inventory tick down.',
        replaces: ['Fishbowl', 'QuickBooks Inventory', 'Sortly'],
        highlights: ['Job consumption', 'Per-location stock'],
        route: '/inventory',
        walkthrough: 'inventory',
      },
      {
        name: 'Labor Rates',
        icon: 'Hammer',
        summary: "Named labor rates ('Lead Tech', 'Apprentice', 'Travel') with billable rate + cost rate + multiplier for accurate gross-margin math.",
        replaces: ['QuickBooks service items', 'ServiceTitan labor'],
        highlights: ['Cost vs billable', 'Multipliers'],
        route: '/products',
      },
    ],
  },
  {
    category: 'Books & Accounting',
    summary: 'Plaid-synced bank feeds, AI-categorized transactions, IRS-ready P&L — your QuickBooks replacement.',
    features: [
      {
        name: 'Books',
        icon: 'BookOpen',
        summary: 'The full accounting cockpit — chart of accounts, P&L by month/quarter/year, bank reconciliation, transaction edit modal with IRS Form 1065 line mapping.',
        replaces: ['QuickBooks Online', 'Xero', 'Wave'],
        highlights: ['Form 1065 line mapping', 'Bank reconciliation', 'Job allocation'],
        route: '/books',
        walkthrough: 'books',
      },
      {
        name: 'Plaid Bank Sync',
        icon: 'Landmark',
        summary: 'Connect any bank in 30 seconds — Plaid pulls transactions nightly, AI categorizes them, and a learning rules engine remembers your corrections.',
        replaces: ['QuickBooks bank feeds', 'Xero bank feeds'],
        highlights: ['Plaid OAuth', 'AI category + confidence', 'Learning rules'],
        route: '/books',
        walkthrough: 'plaid-sync',
      },
      {
        name: 'Plaid Invoice Matching',
        icon: 'Link',
        summary: 'Incoming bank deposits auto-match to outstanding customer invoices so AR closes itself.',
        replaces: ['QuickBooks Auto-Match', 'Xero bank rules'],
        highlights: ['Auto-match deposits', 'Reduces AR aging'],
        route: '/books',
      },
      {
        name: 'Expenses',
        icon: 'DollarSign',
        summary: 'Track every business expense — receipt photo, payee (structured), category, tax category, job allocation — manually or via Plaid.',
        replaces: ['Expensify', 'QuickBooks Expenses', 'Ramp'],
        highlights: ['Receipt photos', 'Job allocation', 'Split categories'],
        route: '/expenses',
        walkthrough: 'expenses',
      },
      {
        name: 'Invoices',
        icon: 'Receipt',
        summary: 'Send a Stripe-powered invoice with due date, payment plan support, email tracking, deposit/progress/final typing, and one-click pay link.',
        replaces: ['QuickBooks Invoicing', 'Stripe Invoicing', 'FreshBooks'],
        highlights: ['Stripe payment links', 'Payment plans', 'Email open tracking', 'Conversation thread per invoice'],
        route: '/invoices',
        walkthrough: 'invoices',
      },
      {
        name: 'Deposits & Lead Payments',
        icon: 'CreditCard',
        summary: 'Capture deposits / pre-job payments tied to the lead before the job exists, with receipt photo and refund support.',
        replaces: ['Square deposits', 'Stripe Payment Intents'],
        highlights: ['Pre-job deposits', 'Refund tracking'],
        route: null,
      },
      {
        name: 'Payments & Refunds',
        icon: 'Wallet',
        summary: 'Every payment (Stripe, ACH, check, cash) and refund logged with source-system traceability and Stripe refund linkage.',
        replaces: ['Stripe Dashboard', 'QuickBooks Payments'],
        highlights: ['Stripe refund column', 'Multi-method'],
        route: '/invoices',
      },
      {
        name: 'Frankie The AI CFO',
        icon: 'Bot',
        summary: "Ask Frankie 'why is cash tight this month?' in plain English — he tracks AR/AP aging, runs job profitability, detects expense anomalies, and auto-sends collection reminders.",
        replaces: ['Pilot.com', 'Bench', 'fractional CFO'],
        highlights: ['Plain-English Q&A', 'Auto-collections', 'Job profitability'],
        route: '/agents/frankie',
        walkthrough: 'frankie',
      },
      {
        name: 'Transaction Job Allocations',
        icon: 'PieChart',
        summary: 'Allocate a single Plaid transaction across multiple jobs / categories so job costing actually reflects reality.',
        replaces: ['QuickBooks Class Tracking', 'Xero tracking categories'],
        highlights: ['Multi-job split', 'Drives job profitability'],
        route: '/books',
      },
    ],
  },
  {
    category: 'Payroll, HR & Onboarding',
    summary: 'Time clock to W-2 — a Gusto-and-BambooHR replacement built for trades.',
    features: [
      {
        name: 'Time Clock',
        icon: 'Clock',
        summary: 'Web + mobile clock in/out with GPS lat/lng, address reverse-geocode, lunch breaks, and admin-side adjustments with audit trail.',
        replaces: ['ADP RUN', 'When I Work', 'TimeClock Plus', 'Buddy Punch'],
        highlights: ['GPS on punch', 'Lunch breaks', 'Adjustment audit'],
        route: '/time-clock',
        walkthrough: 'time-clock',
      },
      {
        name: 'Background Location Pings',
        icon: 'Navigation',
        summary: "While clocked in, the field tech's phone drops a GPS ping every few minutes — proof of work, time-on-site math, and route reconstruction.",
        replaces: ['Samsara driver tracking', 'TSheets GPS'],
        highlights: ['Background pings', 'Time-on-site math', 'Route playback'],
        route: '/time-clock',
      },
      {
        name: 'Clock-Out Verification',
        icon: 'ShieldCheck',
        summary: 'An admin enforces clockout verification (with override flow) so nobody ghosts a shift — flagged unverified clockouts hit the payroll inbox.',
        replaces: ['ADP supervisor approval', 'TSheets approvals'],
        highlights: ['Enforce rule', 'Override flow', 'Flagged list'],
        route: null,
      },
      {
        name: 'Payroll Runs',
        icon: 'DollarSign',
        summary: 'Run payroll — pulls hours from time clock, computes regular/OT/PTO/bonus/commission, calculates federal + state withholding using IRS Pub 15-T percentage method.',
        replaces: ['Gusto', 'ADP RUN', 'OnPay', 'Paychex'],
        highlights: ['IRS Pub 15-T math', 'Multi-state withholding', 'Overtime mode'],
        route: null,
        walkthrough: 'payroll',
      },
      {
        name: 'Payroll Inbox',
        icon: 'Inbox',
        summary: "A single 'what to do today' inbox — tax deposit deadlines, 941 filings, new-hire reports, unverified clockouts, expiring I-9s — driven by the payroll_tax_liabilities table.",
        replaces: ['Gusto Inbox', 'ADP compliance dashboard'],
        highlights: ['EFTPS / state deposits', 'Form 941 / 940 / TC-941 reminders', 'I-9 Section 2 deadlines'],
        route: null,
      },
      {
        name: 'Tax Engine & Filings',
        icon: 'FileBadge',
        summary: 'Generates 941, 940, W-2, W-3, TC-941, 1099-NEC, 1096 PDFs with snapshot data, filing status tracking, and amendment support.',
        replaces: ['Gusto tax filings', 'ADP year-end', 'TaxBandits'],
        highlights: ['W-2 / W-3 / 1099-NEC / 1096', 'Amendment tracking', 'PDF snapshots'],
        route: null,
        walkthrough: 'tax-filings',
      },
      {
        name: 'Direct Deposit',
        icon: 'Banknote',
        summary: 'Encrypted ACH account + routing per employee (pgcrypto, last-4 only displayed), with deposit authorization form signed in onboarding.',
        replaces: ['Gusto direct deposit', 'ADP direct deposit'],
        highlights: ['pgcrypto encryption', 'Last-4 display', 'Signed auth form'],
        route: '/employees',
      },
      {
        name: 'Paystubs',
        icon: 'FileText',
        summary: 'Per-pay-period paystub with gross/net, federal + state withholding, FICA, Medicare, FUTA, SUI, pre-tax + post-tax deductions, and amendment trail.',
        replaces: ['Gusto paystubs', 'ADP MyADP'],
        highlights: ['Full tax breakdown', 'Amendment lineage', 'Net pay computed'],
        route: null,
      },
      {
        name: 'My Pay',
        icon: 'Wallet',
        summary: "Each employee's self-service view of pending commissions, bonuses, paystubs, and hours — so Tech Mike can check his check without bugging Alayda.",
        replaces: ['Gusto employee app', 'ADP MyADP'],
        highlights: ['Self-service paystubs', 'Pending commission view'],
        route: null,
        walkthrough: 'my-pay',
      },
      {
        name: 'Bonus & Piece Rate',
        icon: 'Gift',
        summary: 'Per-employee bonus rules and piece-rate pay (per fixture installed, per panel done) computed automatically from job-line completion.',
        replaces: ['Gusto bonus runs', 'manual spreadsheets'],
        highlights: ['Per-fixture piece rate', 'Auto-compute from job lines'],
        route: null,
      },
      {
        name: 'Commissions',
        icon: 'Percent',
        summary: 'Multi-tier commission structure — goods %, services %, software %, lead-source flat, setter per-meeting — all per-employee.',
        replaces: ['Spiff', 'QuotaPath', 'ServiceTitan commissions'],
        highlights: ['Multi-tier', 'Setter + closer split', 'Utility processor commission'],
        route: null,
        walkthrough: 'commissions',
      },
      {
        name: 'PTO Tracking',
        icon: 'Sun',
        summary: 'Per-employee PTO accrual, used, and remaining with time-off request workflow.',
        replaces: ['BambooHR PTO', 'Gusto PTO'],
        highlights: ['Accrual + used', 'Request workflow'],
        route: '/employees',
      },
      {
        name: 'Employee Onboarding Portal',
        icon: 'UserPlus',
        summary: "Admin clicks 'Send onboarding link' — new hire's phone walks them through W-4, state withholding, direct deposit, I-9 Section 1, handbook signature, and training, all in one mobile flow with magic-link auth.",
        replaces: ['BambooHR onboarding', 'Gusto onboarding', 'Rippling'],
        highlights: ['14-day magic link', 'Per-step audit', 'Phone-first'],
        route: null,
        walkthrough: 'onboarding-portal',
      },
      {
        name: 'Signed Documents Vault',
        icon: 'Archive',
        summary: 'Every signed form (W-4, I-9, direct deposit auth, handbook ack, ICA, custom policy) stored with PDF, signature image, IP, UA, consent text — ESIGN-Act compliant.',
        replaces: ['DocuSign vault', 'BambooHR documents'],
        highlights: ['ESIGN audit fields', 'Supersession chain', 'Per-employee folder'],
        route: '/employees',
      },
      {
        name: 'I-9 Section 2 Tracking',
        icon: 'AlertCircle',
        summary: 'Section 1 lands → Section 2 deadline auto-calculated as hire date + 3 business days → admin gets a payroll inbox task to physically inspect ID.',
        replaces: ['BambooHR I-9', 'manual deadline tracking'],
        highlights: ['Auto-deadline', 'Inbox reminder'],
        route: null,
      },
      {
        name: 'Contractor W-9 & 1099',
        icon: 'FileSignature',
        summary: '1099 contractors fill out a W-9 through the same onboarding portal — TIN, address, tax classification — feeding year-end 1099-NEC generation.',
        replaces: ['Track1099', 'Tax1099.com', 'Gusto contractor'],
        highlights: ['W-9 capture', '1099-NEC + 1096', 'Tax classification'],
        route: '/employees',
      },
      {
        name: 'Independent Contractor Agreement',
        icon: 'ScrollText',
        summary: 'ICA signed in the onboarding flow, stored in the signed_documents vault with timestamp + IP.',
        replaces: ['DocuSign templates', 'PandaDoc'],
        highlights: ['ESIGN audit', 'Vault storage'],
        route: null,
      },
      {
        name: 'Workers Comp Class Codes',
        icon: 'HardHat',
        summary: 'Per-employee workers comp class code on the employee record + per-company class code JSON for filing-time reporting.',
        replaces: ['Hourly.io', 'AP Intego'],
        highlights: ['Per-employee codes', 'Filing-ready JSON'],
        route: '/employees',
      },
      {
        name: 'Background Check Authorization',
        icon: 'ShieldCheck',
        summary: 'Optional onboarding step — captures FCRA-compliant authorization signature so admins can run a Checkr / Sterling background check.',
        replaces: ['Checkr request flow', 'BambooHR background'],
        highlights: ['FCRA consent text', 'Audit trail'],
        route: null,
      },
      {
        name: 'Handbook Acknowledgment',
        icon: 'BookMarked',
        summary: 'Employee scrolls and signs the company handbook in onboarding; vault keeps the signed PDF with consent text for the life of the employment.',
        replaces: ['BambooHR policy sign-offs', 'DocuSign'],
        highlights: ['Scroll-to-sign', 'Per-policy supersession'],
        route: null,
      },
      {
        name: 'Onboarding Training Videos',
        icon: 'PlayCircle',
        summary: 'Admin drops Loom / YouTube video URLs into settings; new hires watch them as the final onboarding step before they can finish.',
        replaces: ['Trainual', 'BambooHR Learning', 'Lessonly'],
        highlights: ['Configurable video URLs', 'Acknowledgment recorded'],
        route: '/settings',
      },
      {
        name: 'Employees',
        icon: 'UserCog',
        summary: 'The HR roster — role, access level, tax classification, hire date, emergency contact, pay setup, photo, last-login.',
        replaces: ['BambooHR', 'Gusto employees', 'Rippling'],
        highlights: ['Multi-pay-type flags', 'HR access flag', 'Tax classification'],
        route: '/employees',
        walkthrough: 'employees',
      },
      {
        name: 'Time Log',
        icon: 'List',
        summary: "Admin grid of all time-clock entries with notes, GPS, adjustment history — Alayda's everyday tool for fixing missed punches.",
        replaces: ['When I Work timesheets', 'TSheets admin'],
        highlights: ['Per-entry notes', 'Adjustment audit'],
        route: null,
      },
    ],
  },
  {
    category: 'AI Crew',
    summary: 'Specialist AI agents you recruit a la carte — each one replaces a whole SaaS category.',
    features: [
      {
        name: 'Arnie',
        icon: 'Bot',
        summary: "The general-purpose AI assistant — chat with your business data, ask 'how many jobs did we close last quarter?', or 'draft a quote for this lead'.",
        replaces: ['ChatGPT Team', 'Microsoft Copilot'],
        highlights: ['Reads your data', 'Floating panel', 'Per-conversation history'],
        route: null,
        status: 'shipped',
      },
      {
        name: 'Lenard The Lighting Auditor',
        icon: 'Lightbulb',
        summary: 'Snaps photos, identifies fixtures, counts bulbs, recommends LEDs, and calculates the utility rebate — your LED retrofit specialist.',
        replaces: ['Snugg Pro', 'Rifeline', 'manual energy audits'],
        highlights: ['AI fixture ID', 'Rebate math', 'Public agent pages'],
        route: null,
        status: 'shipped',
      },
      {
        name: 'Freddy The Fleet Manager',
        icon: 'Truck',
        summary: 'Vehicles verified, maintenance managed, fuel logged, drivers scored — phone-GPS-only fleet ops without the $40/mo/truck hardware.',
        replaces: ['Fleetio', 'Samsara', 'Verizon Connect'],
        highlights: ['No hardware', 'Photo inspections', 'Driver scorecard'],
        route: '/agents/freddy',
        status: 'shipped',
      },
      {
        name: 'Conrad Connect',
        icon: 'Mail',
        summary: 'AI email-marketing agent — writes campaigns, syncs contacts to Constant Contact, tracks engagement, suggests follow-up timing.',
        replaces: ['Constant Contact', 'Mailchimp', 'Klaviyo'],
        highlights: ['Constant Contact OAuth', 'AI copywriting', 'Smart send-time'],
        route: '/agents/conrad-connect',
        status: 'shipped',
        walkthrough: 'conrad',
      },
      {
        name: 'Victor The Verification Agent',
        icon: 'Camera',
        summary: 'Before/after photo comparison — Victor scores completed work against a checklist, flags issues, and produces a verification report customers (and you) can trust.',
        replaces: ['CompanyCam verification', 'manual QA walkthroughs'],
        highlights: ['Photo-to-photo AI', 'Per-job checklist', 'Score + grade'],
        route: null,
        status: 'shipped',
        walkthrough: 'victor',
      },
      {
        name: 'Frankie The AI CFO',
        icon: 'DollarSign',
        summary: "Plain-English finance Q&A, AR/AP aging, expense anomaly detection, auto-sent collection reminders, job profitability — the CFO you don't have to hire.",
        replaces: ['Pilot.com', 'Bench', 'fractional CFO'],
        highlights: ['Cash flow', 'Auto-collections', 'Anomaly detection'],
        route: '/agents/frankie',
        status: 'shipped',
      },
      {
        name: 'Zach The Yard Yeti',
        icon: 'Sprout',
        summary: "Lawn-care specialist — measures turf from aerial imagery, drops an instant quote in the prospect's inbox, runs visits and treatments.",
        replaces: ['Service Autopilot', 'LawnPro', 'GreenPal'],
        highlights: ['AI yard measure', 'Instant quote page', 'Visit + treatment log'],
        route: '/agents/zach',
        status: 'shipped',
      },
      {
        name: 'Walter The Window Wizard',
        icon: 'Grid3X3',
        summary: 'Analyzes building photos to count panes, identify window types, and generate accurate window-cleaning quotes.',
        replaces: ['WinCleaner pricing', 'manual pane counts'],
        highlights: ['Pane counter', 'Auto-quote'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Paula The Paint Pro',
        icon: 'Paintbrush',
        summary: 'Measures paintable surfaces from photos, identifies materials, calculates paint requirements and quote totals.',
        replaces: ['PaintScout', 'manual takeoff'],
        highlights: ['Surface measurement', 'Paint calc'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Roger The Roof Reader',
        icon: 'Home',
        summary: 'Aerial / ground roof analysis — identifies materials, spots damage, measures area for roofing estimates.',
        replaces: ['EagleView', 'Hover', 'RoofSnap'],
        highlights: ['Aerial measurement', 'Damage detection'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Clara The Clean Queen',
        icon: 'Sparkles',
        summary: 'Commercial cleaning estimator — identifies space types from photos, estimates clean time, generates a service quote.',
        replaces: ['CleanGuru', 'Janitorial Manager'],
        highlights: ['Space-type AI', 'Time estimates'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Pete The Pipe Whisperer',
        icon: 'Droplets',
        summary: 'Plumbing diagnostician — identifies fixtures, spots potential leaks, recommends repairs from your photos.',
        replaces: ['ServiceTitan plumbing forms', 'manual diagnostics'],
        highlights: ['Leak detection', 'Repair recommendations'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Eddie The Amp Analyst',
        icon: 'Zap',
        summary: 'Electrical analyst — reads panels, identifies NEC violations, recommends upgrades from a photo.',
        replaces: ['manual electrical surveys'],
        highlights: ['Panel reader', 'Violation flagging'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Mason The Stone Sage',
        icon: 'Mountain',
        summary: 'Concrete + brick specialist — spots cracks, assesses damage severity, measures repair areas.',
        replaces: ['manual masonry takeoff'],
        highlights: ['Crack detection', 'Severity scoring'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Frank The Floor Finder',
        icon: 'Square',
        summary: 'Identifies flooring materials, measures rooms, and spots damage that needs repair vs replacement.',
        replaces: ['manual flooring takeoff'],
        highlights: ['Material ID', 'Room measurement'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Harry The Climate Commander',
        icon: 'Thermometer',
        summary: 'HVAC specialist — identifies make/model from data plates, recommends service, sizes replacements.',
        replaces: ['ServiceTitan HVAC forms', 'manual nameplate lookups'],
        highlights: ['Data plate reader', 'Service recommendations'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Gus The Gutter Guru',
        icon: 'CloudRain',
        summary: 'Measures linear feet of gutter, counts downspouts, spots clogs and damage from photos.',
        replaces: ['manual gutter measurement'],
        highlights: ['Linear-foot measurement', 'Clog detection'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Sammy The Safety Scout',
        icon: 'ShieldCheck',
        summary: 'Job-site safety expert — identifies OSHA hazards, checks compliance, and generates pre-job safety reports.',
        replaces: ['SafetyCulture (iAuditor)', 'Procore safety'],
        highlights: ['OSHA hazard ID', 'Compliance reports'],
        route: '/base-camp',
        status: 'coming_soon',
      },
      {
        name: 'Base Camp',
        icon: 'Tent',
        summary: 'The marketplace where companies browse and recruit AI agents — pay monthly or yearly, agents activate and appear in your sidebar.',
        replaces: ['app marketplaces (Salesforce AppExchange, etc.)'],
        highlights: ['A la carte pricing', 'Per-agent activation'],
        route: '/base-camp',
      },
      {
        name: 'My Crew',
        icon: 'Users',
        summary: 'Manage your currently-recruited agents — pause, configure menu placement, see subscription status.',
        replaces: ['app subscription dashboards'],
        highlights: ['Per-agent settings', 'Subscription status'],
        route: '/my-crew',
      },
    ],
  },
  {
    category: 'EOS & Business Operations',
    summary: 'The Entrepreneurial Operating System, baked into the app — no more $99/mo for Bloom or Ninety.',
    features: [
      {
        name: 'Vision (V/TO)',
        icon: 'Eye',
        summary: 'Core values, core focus, 10-year target, marketing strategy, 3-year picture, 1-year plan — your entire Vision/Traction Organizer lives in one page.',
        replaces: ['EOSOne', 'Ninety.io', 'Bloom Growth'],
        highlights: ['Full V/TO', 'Per-company'],
        route: '/admin/eos',
      },
      {
        name: 'Rocks',
        icon: 'Target',
        summary: 'Quarterly Rocks per person and per company, with on-track / off-track status and quarterly carry-over.',
        replaces: ['EOSOne Rocks', 'Ninety Rocks'],
        highlights: ['Per-quarter', 'Owner assigned'],
        route: '/admin/eos',
      },
      {
        name: 'Scorecard',
        icon: 'BarChart3',
        summary: 'Weekly numbers (leads, jobs, closed-won, AR) auto-populated from real Job Scout data — no more copy-paste from QuickBooks.',
        replaces: ['EOSOne Scorecard', 'Ninety Scorecard'],
        highlights: ['Auto-populated from data', 'Weekly cadence'],
        route: '/admin/eos',
      },
      {
        name: 'Issues / IDS',
        icon: 'AlertTriangle',
        summary: 'Issues list with Identify-Discuss-Solve workflow for L10 meetings.',
        replaces: ['EOSOne Issues', 'Ninety Issues'],
        highlights: ['IDS workflow'],
        route: '/admin/eos',
      },
      {
        name: 'Accountability Chart',
        icon: 'Network',
        summary: 'Visual org chart with seat / role / accountability per box — the EOS accountability chart, not a generic org chart.',
        replaces: ['Pingboard', 'EOSOne org chart'],
        highlights: ['Seat + role + accountability'],
        route: '/admin/eos',
      },
      {
        name: 'L10 Meetings & To-dos',
        icon: 'Calendar',
        summary: 'Run your Level-10 meeting with built-in agenda + timer, capture to-dos with owners and 7-day deadlines.',
        replaces: ['EOSOne L10', 'Ninety meetings'],
        highlights: ['Meeting timer', 'To-do follow-through'],
        route: '/admin/eos',
      },
      {
        name: 'People Analyzer & Quarterly Convos',
        icon: 'UserCheck',
        summary: 'GWC + core-values ratings per employee and quarterly conversation records — the EOS People component.',
        replaces: ['EOSOne People Analyzer', '15Five'],
        highlights: ['GWC ratings', 'Quarterly conversations'],
        route: '/admin/eos',
      },
    ],
  },
  {
    category: 'PWA, Offline & Mobile',
    summary: 'Built for field techs on flaky LTE — clock in, photograph, sign offline, sync later.',
    features: [
      {
        name: 'Offline Mode',
        icon: 'CloudOff',
        summary: 'Every write hits an IndexedDB sync queue first — clock-ins, photos, signatures, time-log notes all queue and replay when the truck pulls back into LTE.',
        replaces: ['HousecallPro offline (none)', 'Jobber offline (none)'],
        highlights: ['IndexedDB queue', '30-second auto-sync', 'Persistent storage request'],
        route: null,
      },
      {
        name: 'Photo Queue',
        icon: 'Image',
        summary: "Photos compress and queue locally — drop into a basement with no signal, snap 50 audit photos, and they upload as soon as you're back on the highway.",
        replaces: ['CompanyCam queue', 'manual photo upload'],
        highlights: ['Compressed queue', 'Survives app restart'],
        route: null,
      },
      {
        name: 'Install as App (PWA)',
        icon: 'Download',
        summary: 'Add to Home Screen on iOS / Android — full-screen app, push notifications, offline shell, no app store.',
        replaces: ['native iOS / Android apps'],
        highlights: ['A2HS', 'Push-capable', 'No app store'],
        route: null,
      },
      {
        name: 'Cached Session',
        icon: 'Wifi',
        summary: 'Persisted Zustand store + tolerant auth refresh means a transient signal blip never kicks a tech to login mid-shift.',
        replaces: ['session-timeout pain in HCP / Jobber'],
        highlights: ['Tolerant refresh', 'Cached employee record'],
        route: null,
      },
    ],
  },
  {
    category: 'Admin & Multi-tenant',
    summary: "Developer console, tenant isolation, audit logs, beta invite codes — the back-end you'd build yourself.",
    features: [
      {
        name: 'Data Console',
        icon: 'Database',
        summary: 'A developer-only admin cockpit — SQL runner, table browser, bulk ops, saved queries, migrations, audit log, products manager, users, companies, feedback, agents registry, utilities lookup.',
        replaces: ['Retool', 'Supabase Studio', 'phpMyAdmin'],
        highlights: ['SQL runner', 'Saved queries', 'Per-table browser', 'Audit log'],
        route: '/admin/data-console',
      },
      {
        name: 'Tenant Isolation (RLS)',
        icon: 'Shield',
        summary: "Every table enforces tenant_isolation via Postgres RLS keyed off current_user_company_ids() — one slip can't leak one customer's data to another.",
        replaces: ['application-layer auth checks'],
        highlights: ['Postgres-enforced', 'FORCE RLS on tables', 'Developer bypass'],
        route: null,
      },
      {
        name: 'Beta Invite Codes',
        icon: 'Key',
        summary: 'Time-limited, usage-capped invite codes for the closed beta — generated in the admin console, redeemed at signup.',
        replaces: ['Waitlist tools', 'Customer.io invite flows'],
        highlights: ['Per-code usage cap', 'Expiration'],
        route: '/admin/data-console',
      },
      {
        name: 'Employee Invitations',
        icon: 'Send',
        summary: 'Invite a new teammate by email with a magic link, pre-assigned role and access level, expiring in 7 days.',
        replaces: ['BambooHR invites', 'Gusto invites'],
        highlights: ['Magic link', 'Role pre-set'],
        route: '/employees',
      },
      {
        name: 'Stripe Master Billing',
        icon: 'CreditCard',
        summary: "Job Scout bills tenants on its own master Stripe account — trial period, status banner, payment method on file — separate from the tenant's own customer-facing Stripe.",
        replaces: ['Chargebee', 'Stripe Billing console'],
        highlights: ['Trial tracking', 'Trial banner', 'Past-due states'],
        route: '/settings',
      },
      {
        name: 'Subscription Tiers',
        icon: 'Layers',
        summary: "Plan tiers ('Boss' grandfather, etc.) gate features per company — managed via billing_status and plan flags.",
        replaces: ['Chargebee plans', 'Stripe Products'],
        highlights: ['Per-company plan', 'Grandfathered tenants'],
        route: '/settings',
      },
      {
        name: 'Audit Log',
        icon: 'ScrollText',
        summary: 'Every table mutation hits an audit_log trigger — who changed what, when — visible in the Data Console.',
        replaces: ['application logging', 'Postgres audit extensions'],
        highlights: ['Trigger-based', 'Per-table'],
        route: '/admin/data-console',
      },
      {
        name: 'Migrations Browser',
        icon: 'GitMerge',
        summary: "View applied migrations in the Data Console — no more SSH'ing to check schema state.",
        replaces: ['psql migrations table queries'],
        highlights: ['Per-migration status', 'In-app'],
        route: '/admin/data-console',
      },
      {
        name: 'Feedback Inbox',
        icon: 'MessageCircle',
        summary: 'Users hit the floating Feedback button, drop a message + screenshot, and it lands in an admin inbox with reply threading.',
        replaces: ['Intercom', 'Canny', 'UserBack'],
        highlights: ['Floating button', 'Reply thread', 'Screenshots'],
        route: '/admin/data-console',
      },
      {
        name: 'Help & Walkthroughs',
        icon: 'HelpCircle',
        summary: 'In-app help center with guides, diagrams, and how-the-app-works walkthroughs — visible to all employees.',
        replaces: ['Intercom Articles', 'Notion docs'],
        highlights: ['Per-page hints', 'Diagrams'],
        route: '/admin/help',
      },
      {
        name: 'Video Library',
        icon: 'PlayCircle',
        summary: 'Loom-style feature gallery — every Job Scout capability with a short video and the market tool it replaces.',
        replaces: ['Loom for marketing', 'YouTube playlists'],
        highlights: ['Per-feature videos', 'Replaces-X badges'],
        route: '/admin/videos',
      },
      {
        name: 'Global Search',
        icon: 'Search',
        summary: 'Cmd-K-style search bar in the sidebar — jump to any customer, lead, job, invoice, or page.',
        replaces: ['Algolia', 'Linear-style command palette'],
        highlights: ['Fuzzy match', 'Cross-entity'],
        route: null,
      },
      {
        name: 'HCP Importer',
        icon: 'Upload',
        summary: 'One-shot importer for HousecallPro tenants — customers, jobs, quotes, invoices, payments all land with source_system + source_id traceability so you can re-run safely.',
        replaces: ['custom CSV exports from HCP', 'Zapier hand-rolls'],
        highlights: ['Idempotent upserts', 'Source traceability', 'Line-item fidelity'],
        route: '/admin/data-console',
      },
    ],
  },
  {
    category: 'Integrations',
    summary: 'Plaid, Stripe, Google, Twilio, SendGrid, Apollo, Constant Contact, Gemini — wired in, ready to flip on.',
    features: [
      {
        name: 'Plaid',
        icon: 'Landmark',
        summary: 'Bank-feed sync for Books, AI categorization, and invoice auto-matching.',
        replaces: ['QuickBooks bank feeds', 'Yodlee'],
        highlights: ['OAuth bank linking', 'Nightly sync', 'Auto-match deposits'],
        route: '/books',
      },
      {
        name: 'Stripe',
        icon: 'CreditCard',
        summary: 'Stripe Payment Links on every invoice for one-click pay; refunds + ACH tracked back to the source payment; per-tenant Stripe keys keep your money in your account.',
        replaces: ['Square', 'Authorize.net'],
        highlights: ['Payment Links', 'Refund tracking', 'Per-tenant keys'],
        route: '/invoices',
      },
      {
        name: 'Google Calendar',
        icon: 'Calendar',
        summary: 'Two-way sync per-employee — appointments land on their personal Google Calendar, edits replay back.',
        replaces: ['Calendly integrations', 'Acuity sync'],
        highlights: ['OAuth per-user', 'Two-way sync'],
        route: '/appointments',
      },
      {
        name: 'Google Maps',
        icon: 'Map',
        summary: 'Reverse geocode clock-in punches, render routes on a map, drop pins on properties.',
        replaces: ['Mapbox', 'manual address entry'],
        highlights: ['Reverse geocode', 'Route maps', 'Property pins'],
        route: null,
      },
      {
        name: 'Twilio SMS',
        icon: 'MessageSquare',
        summary: 'Outbound SMS for appointment reminders, onboarding magic links, collection reminders, and customer-portal notifications.',
        replaces: ['Podium', 'EZTexting'],
        highlights: ['Magic-link delivery', 'Reminders'],
        route: null,
      },
      {
        name: 'SendGrid Email',
        icon: 'Mail',
        summary: "Transactional email for invoices, estimates, magic links, onboarding, and Frankie's collection reminders.",
        replaces: ['Mailgun', 'Postmark'],
        highlights: ['Open tracking', 'Bounce handling'],
        route: null,
      },
      {
        name: 'Gemini AI',
        icon: 'Sparkles',
        summary: 'Vision + text model behind Lenard (fixture ID), Zach (yard measure), Victor (verification), Conrad (copywriting), and Arnie (chat).',
        replaces: ['GPT-4 vision direct integration'],
        highlights: ['Vision + text', 'Per-agent prompting'],
        route: null,
      },
      {
        name: 'Apollo.io',
        icon: 'Telescope',
        summary: 'B2B prospect search + email/phone reveal feeding the lead setter.',
        replaces: ['ZoomInfo', 'Lusha'],
        highlights: ['Per-tenant API key', 'Credit balance display'],
        route: '/lead-setter',
      },
      {
        name: 'Constant Contact',
        icon: 'Send',
        summary: 'OAuth-linked email marketing via Conrad — campaigns, contacts, templates, engagement stats roundtrip with your CC account.',
        replaces: ['Mailchimp', 'Klaviyo'],
        highlights: ['OAuth', 'Contact sync', 'Campaign mirroring'],
        route: '/agents/conrad-connect',
      },
    ],
  },
  {
    category: 'Reports & Insights',
    summary: 'Owner-grade dashboards on top of your operational data — no BI tool required.',
    features: [
      {
        name: 'Dashboard',
        icon: 'LayoutDashboard',
        summary: 'The home page — leads, jobs, AR, this-week metrics, and per-employee activity in one glance.',
        replaces: ['custom Looker dashboards', 'QuickBooks home'],
        highlights: ['Real-time', 'Role-filtered'],
        route: '/',
      },
      {
        name: 'Reports',
        icon: 'BarChart3',
        summary: 'Pre-built reports — sales pipeline, AR aging, job profitability, commission summary, payroll summary, fleet costs — with per-report deep links.',
        replaces: ['QuickBooks Reports', 'Tableau'],
        highlights: ['Drill-into-row', 'Per-report URL'],
        route: '/reports',
        walkthrough: 'reports',
      },
      {
        name: 'Frankie Insights',
        icon: 'TrendingUp',
        summary: "Anomaly detection + what-if scenarios — Frankie flags 'expenses up 18% in May vs April' before you notice.",
        replaces: ['Domo', 'ProfitWell'],
        highlights: ['Anomaly detection', 'What-if scenarios'],
        route: '/agents/frankie',
      },
      {
        name: 'Company Notifications',
        icon: 'BellRing',
        summary: 'Per-company in-app notification stream — new lead assigned, quote signed, payment received, payroll due — with celebration animations on big wins.',
        replaces: ['Slack notifications', 'Pulse for ServiceTitan'],
        highlights: ['Celebration animations', 'Per-event preferences'],
        route: null,
      },
    ],
  },
]

// Compact summary card stat — number of distinct market tools we replace.
export function getReplacedToolCount(catalog = FEATURE_CATALOG) {
  const tools = new Set()
  for (const cat of catalog) {
    for (const f of cat.features || []) {
      for (const t of f.replaces || []) tools.add(t)
    }
  }
  return tools.size
}

export function getAllReplacedTools(catalog = FEATURE_CATALOG) {
  const tools = new Map() // name -> count of features that replace it
  for (const cat of catalog) {
    for (const f of cat.features || []) {
      for (const t of f.replaces || []) tools.set(t, (tools.get(t) || 0) + 1)
    }
  }
  return [...tools.entries()].sort((a, b) => b[1] - a[1])
}
