-- Bank-deposit ↔ invoice reconciliation columns.
-- Lets the Books page surface unmatched deposits and tie a Plaid transaction
-- to the invoice + payment row it pays for. Drives commission flow: when the
-- match writes a payments row, the existing payment_received commission
-- trigger picks it up automatically.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='plaid_transactions' AND column_name='matched_invoice_id') THEN
    ALTER TABLE plaid_transactions ADD COLUMN matched_invoice_id INT REFERENCES invoices(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='plaid_transactions' AND column_name='matched_payment_id') THEN
    ALTER TABLE plaid_transactions ADD COLUMN matched_payment_id INT REFERENCES payments(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='plaid_transactions' AND column_name='matched_at') THEN
    ALTER TABLE plaid_transactions ADD COLUMN matched_at TIMESTAMPTZ;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='plaid_transactions' AND column_name='matched_by') THEN
    ALTER TABLE plaid_transactions ADD COLUMN matched_by INT REFERENCES employees(id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_plaid_transactions_matched_invoice
  ON plaid_transactions(matched_invoice_id) WHERE matched_invoice_id IS NOT NULL;

-- Payments table: track origin so we can distinguish manual mark-paid clicks
-- from real payment entries from bank-deposit matches. Useful for the audit
-- trail in the Payroll commission-detail view.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='payments' AND column_name='source') THEN
    ALTER TABLE payments ADD COLUMN source TEXT;
    -- 'manual'  = added via Add Payment modal
    -- 'mark_paid' = generated by the Mark as Paid button
    -- 'bank_match' = generated by matching a Plaid deposit to an invoice
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='payments' AND column_name='source_transaction_id') THEN
    ALTER TABLE payments ADD COLUMN source_transaction_id INT REFERENCES plaid_transactions(id);
  END IF;
END $$;
