-- Web Push subscriptions, one row per device per employee.
--
-- A rep can have several (phone, tablet, desktop), and browsers rotate the
-- endpoint without warning, so the endpoint is the identity — not the user.
-- Sends that come back 404/410 mean the browser dropped it; those rows get
-- deleted rather than retried forever.
--
-- Locked down like the other tenant tables from the start: anon has no
-- access, and RLS scopes rows to the caller's own company. lead_follow_ups
-- shipped without that and had to be patched a day later.

create table if not exists public.push_subscriptions (
  id            bigint generated by default as identity primary key,
  company_id    bigint not null,
  employee_id   bigint not null,
  endpoint      text not null unique,
  p256dh        text not null,
  auth          text not null,
  user_agent    text,
  last_sent_at  timestamptz,
  failure_count int not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.push_subscriptions is
  'Web Push endpoints per employee device. Endpoint is unique — browsers rotate it, so re-subscribing upserts rather than duplicating.';

create index if not exists push_subscriptions_company_employee_idx
  on public.push_subscriptions (company_id, employee_id);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon;

do $$ begin
  create policy push_subscriptions_company_rw on public.push_subscriptions
    for all to authenticated
    using (
      company_id in (
        select e.company_id from public.employees e
        where e.email = auth.jwt() ->> 'email'
      )
    )
    with check (
      company_id in (
        select e.company_id from public.employees e
        where e.email = auth.jwt() ->> 'email'
      )
    );
exception when duplicate_object then null; end $$;
