-- Liahona: the map view inside the Sales Pipeline (Board | Liahona toggle).
--
-- Leads only had a free-text address, so nothing could be placed on a map.
-- This adds coordinates to leads (filled by the app's geocoder on demand and
-- when an address is saved) and a territories table for the polygons reps
-- draw or lift from county / utility / ZIP boundaries.
--
-- Multi-tenant from the start: every read filters by company_id.

alter table public.leads add column if not exists latitude   double precision;
alter table public.leads add column if not exists longitude  double precision;
alter table public.leads add column if not exists geocoded_at timestamptz;

comment on column public.leads.latitude    is 'WGS84 latitude of leads.address, filled by the Liahona geocoder. NULL = not yet geocoded.';
comment on column public.leads.longitude   is 'WGS84 longitude of leads.address.';
comment on column public.leads.geocoded_at is 'When latitude/longitude were last computed. Cleared by the app when the address changes.';

-- "Which leads have pins?" for a company is the map's first query.
create index if not exists leads_company_geocoded_idx
  on public.leads (company_id)
  where latitude is not null and longitude is not null;

create table if not exists public.sales_territories (
  id                   bigint generated by default as identity primary key,
  company_id           bigint not null,
  name                 text not null,
  color                text not null default '#5a6349',
  -- GeoJSON Polygon or MultiPolygon, [lng, lat] order per the GeoJSON spec.
  polygon              jsonb not null,
  -- drawn | county | city | zip | utility  (where the shape came from)
  source               text not null default 'drawn',
  owner_id             bigint,
  utility_provider_id  bigint,
  utility_name         text,
  notes                text,
  created_by           bigint,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on table public.sales_territories is
  'Canvassing territories shown on the Liahona map. Polygon is GeoJSON; owner_id and utility_provider_id reference employees / utility_providers.';

create index if not exists sales_territories_company_idx
  on public.sales_territories (company_id);

alter table public.sales_territories enable row level security;

do $$ begin
  create policy sales_territories_rw on public.sales_territories
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
