-- Follow-up history for sales deals.
--
-- leads already had last_contact_at / callback_date / callback_notes, and they
-- are effectively dead: populated on 6, 1 and 0 of 1,716 leads respectively.
-- They failed because they hold ONE value (a rep needs the history, not just
-- the last touch) and because logging meant opening the lead and typing into a
-- date field. This table holds one row per touch so the history is real, and
-- the UI logs a row in one tap.
--
-- Multi-tenant from the start: every read filters by company_id.

create table if not exists public.lead_follow_ups (
  id                bigint generated by default as identity primary key,
  company_id        bigint not null,
  lead_id           bigint,
  job_id            bigint,
  employee_id       bigint,
  contacted_at      timestamptz not null default now(),
  method            text not null default 'call',
  note              text,
  next_follow_up_at timestamptz,
  outcome           text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  -- A follow-up has to be about something.
  constraint lead_follow_ups_target_check check (lead_id is not null or job_id is not null)
);

comment on table public.lead_follow_ups is
  'One row per follow-up touch on a lead or job. Replaces the single-value leads.last_contact_at / callback_notes, which could not hold a history.';
comment on column public.lead_follow_ups.method is
  'call | email | text | visit | voicemail | other';
comment on column public.lead_follow_ups.next_follow_up_at is
  'When the rep intends to follow up next. Drives the "due" state on the pipeline Follow-up column.';

-- The pipeline asks "latest touch per lead, for this company" on every load.
create index if not exists lead_follow_ups_company_lead_idx
  on public.lead_follow_ups (company_id, lead_id, contacted_at desc);
create index if not exists lead_follow_ups_company_job_idx
  on public.lead_follow_ups (company_id, job_id, contacted_at desc);
-- "What's due?" across the company.
create index if not exists lead_follow_ups_due_idx
  on public.lead_follow_ups (company_id, next_follow_up_at)
  where next_follow_up_at is not null;

alter table public.lead_follow_ups enable row level security;

do $$ begin
  create policy lead_follow_ups_rw on public.lead_follow_ups
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
